### PR TITLE
Fix Some Sound Effects Still In English

### PR DESCRIPTION
**Pull request by Emalcat**

### CODE REVIEW

**Comment by wagrenier** [comment]
Adjusted the title to better reflect what this fix does. Were you able to test the fix?

**Comment by Emalcat** [comment]
Yes, I didn't find anything wrong
not a full playthough obliously

**Comment by wagrenier** [comment]
Merged

**Comment by wagrenier** [comment]
I'll have to migrate to the new version of dotnet first then I'll create a new release. I might have a save somewhere near where you heard the sound effect in english.

**Pull request merged**
